### ISSUE TITLE
json files with no validKeys incompatible with rollup 0.37.0

### ISSUE THREAD

**Issue by btakita** [rollup/rollup-plugin-json#19]
ExportDefaultDeclaration expects export default to be at the beginning of the string.

https://github.com/rollup/rollup/blob/8466b4ce56415f27687842b3177138929efee62c/src/ast/nodes/ExportDefaultDeclaration.js#L56

Either we need to `.trim()` the string or guard against `namedExports` being empty causing an empty first line at:

https://github.com/rollup/rollup-plugin-json/blob/master/src/index.js#L147

**Comment by kzc** [comment]
See also: https://github.com/rollup/rollup/issues/1146

**Comment by kzc** [comment]
See also: https://github.com/rollup/rollup/pull/1152

**Comment by btakita** [comment]
That works for me.
