### ISSUE TITLE
How to disable the indent change when using this plugin?

### ISSUE THREAD

**Issue by mobilesite** [rollup/rollup-plugin-json#24]
when I'm using this plugin to handle the package.json file, I found it changes the indent to a tab while the origin indent of my source file is two spaces. This caused the eslint throw some errors. So, would you please so kind to tell me is there any option to config the indent of output file from rollup-plugin-json?

**Comment by Rich-Harris** [comment]
Have added an `indent` option in version 2.2.0 which allows you to specify two spaces.

As a general rule, though, you might want to exclude generated code from linting — usually linters only run on your source code.
