### ISSUE TITLE
Support JSON5

### ISSUE THREAD

**Issue by milesj** [rollup/rollup-plugin-json#30]
It's just better all around, plus, it parses regular JSON files, so you can easily support both in parallel: https://github.com/json5/json5

It could either support it by default, or if you don't want to have it as a dependency, support passing the parser as a config option.

```
json({ parser: JSON5.parse })
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
