### ISSUE TITLE
Looking for some clarification on plugin usage...

### ISSUE THREAD

**Issue by ZaLiTHkA** [rollup/rollup-plugin-json#36]
I'm a tad behind the times, only just getting into ES6 now, so I apologise if this seems like an obviously simple point; but like many things in life, it's only easy once you know how..

This plugin's readme starts off with an example of `import { version } from './package.json';`, but then in the usage section it goes into a more verbose example that uses `import json from 'rollup-plugin-json';`.

Is the `package.json` import line also powered by this plugin? Or is that simply part of ES6 itself?

Just to give a bit of context here: I'm working on a proprietary JS library that parses configuration stored inside numerous JSON files, then uses a combination of them to render custom data dashboards.. Once I manage to transpile my project with Rollup, it looks like I *may* be able to use this plugin to bundle a set a predefined widget configurations in a script file. From what I can see, this would effectively allow us to create specialised builds of the overall dashboard project with custom widgets designed for specific customers.

..or am I completely missing the mark here?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
