### ISSUE TITLE
rollup fails when JSON keys contain quotes

### ISSUE THREAD

**Issue by gka** [rollup/rollup-plugin-json#39]
with a JSON file like this (`test.json`):

```json
{
	"a key with \"quotes\"": "foo"
}
```
and a simple `main.js` like this

```js
import data from './test.json';
console.log(data);
```

`rollup-plugin-json` generates invalid code:

```js
(function () {
'use strict';

var data = {
	"a key with "quotes"": "foo"
};

console.log(data);

}());
```

**Comment by lukastaegert** [comment]
I assume that @skindc 's analysis is correct as for me, vanilla rollup-plugin-json correctly escapes quotes. Feel free to reopen if you disagree.
