### ISSUE TITLE
Should pass Array objects to dataToEsm

### ISSUE THREAD

**Issue by yongtw123** [rollup/rollup-plugin-json#47]
Currently according to source, if a parsed JSON were determined to be *not* an Object, as in `Object.prototype.toString.call(data) !== '[object Object]'`, it will not be passed on to `dataToEsm`. However this behavior excludes the case when the JSON is an Array. Since by [definition](https://www.json.org/) JSON can be an object or an array, I believe it's appropriate to modify the conditional to allow `'[object Array]'` or perhaps remove the block altogether. Right now, for instance, a formatted JSON array will not be compacted even if the option `compact: true` is provided since it does not go through `dataToEsm`. Thanks for consideration.

**Comment by danmarshall** [comment]
I'm also trying to import a json file which contains an array. It does not get outputted in the bundle. I also tried the fix in $48 but that did not seem to fix the issue. 🤔

**Comment by atherdon** [comment]
I think I have a similar issue too. I have a few json files, and they contain arrays of objects.
when i run `rollup -c` i get `(json plugin) SyntaxError: Unexpected token ; in JSON at  ...`

**Comment by atherdon** [comment]
@lukastaegert sorry for bothering you. Maybe you can advice what we need to do?

**Comment by lukastaegert** [comment]
Fix at #53
