### ISSUE TITLE
build error with uglifyjs

### ISSUE THREAD

**Issue by mahaina** [rollup/rollup-plugin-json#49]
I'm using rollup to build my library. here is the error
```sh
src/index.js → stdout...
  3590 | 
  3591 | 
> 3592 |        const wrapAnsi16 = (fn, offset) => function () {
       | ^ Unexpected token: keyword (const)
  3593 |          const code = fn.apply(colorConvert, arguments);
  3594 |          return `\u001B[${code + offset}m`;
  3595 |        };
[!] (uglify plugin) Error: Unexpected token: keyword (const)
SyntaxError: Unexpected token: keyword (const)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/jessie/Documents/Projects/test/node_modules/uglify-js/tools/node.js:20:1),
```

and here is the config
```javascript
import alias from 'rollup-plugin-alias';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import {uglify} from 'rollup-plugin-uglify';
import builtins from 'rollup-plugin-node-builtins';
import paths from './paths';

const name = 'test';
const banner = '';

const baseConfig = {
    input: 'src/index.js',
    plugins: [
        alias({
            resolve: ['.js']
        }),
        resolve(),
        babel({
            exclude: 'node_modules/**',
            runtimeHelpers: true
        }),
        commonjs(),
        builtins(),
        process.env.NODE_ENV === 'production' && uglify()
    ]
};
export default [
    {
        ...baseConfig,
        output: [
            {
                name,
                file: `${paths.output}/${name}.js`,
                format: 'umd',
                sourcemap: true
            },
            // cjs and esm version
            {
                file: `${paths.output}/${name}.cjs.js`,
                format: 'cjs',
                banner
            },
            // cjs and esm version
            {
                file: `${paths.output}/${name}.esm.js`,
                format: 'es',
                banner
            }
        ]
    },
    // .min.js
    {
        ...baseConfig,
        output: [
            // umd with compress version
            {
                file: `dist/${name}.min.js`,
                format: 'umd',
                name,
                banner
            }
        ]
    }
];
```
.babelrc
```json
{
    "presets": [
        [
            "@babel/env",
            {
                "modules": false
            }
        ]
    ],
    "plugins": [
        "@babel/proposal-object-rest-spread"
    ]
}
```

deps:
```json
"dependencies": {
    "jsondiffpatch": "^0.3.11"
  },
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/plugin-external-helpers": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/preset-env": "^7.2.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "chalk": "^2.4.1",
    "clean-webpack-plugin": "^1.0.0",
    "cross-env": "^5.2.0",
    "eslint": "^5.9.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-import-resolver-webpack": "^0.10.1",
    "eslint-plugin-import": "^2.14.0",
    "rimraf": "^2.6.2",
    "rollup": "^0.67.4",
    "rollup-plugin-alias": "^1.4.0",
    "rollup-plugin-babel": "^4.0.3",
    "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^3.4.0",
    "rollup-plugin-uglify": "^6.0.0"
  }
```
I can't figure out why.....Please help to check this.

**Comment by mahaina** [comment]
> I'm using rollup to build my library. here is the error
> 
> ```shell
> src/index.js → stdout...
>   3590 | 
>   3591 | 
> > 3592 |        const wrapAnsi16 = (fn, offset) => function () {
>        | ^ Unexpected token: keyword (const)
>   3593 |          const code = fn.apply(colorConvert, arguments);
>   3594 |          return `\u001B[${code + offset}m`;
>   3595 |        };
> [!] (uglify plugin) Error: Unexpected token: keyword (const)
> SyntaxError: Unexpected token: keyword (const)
>     at JS_Parse_Error.get (eval at <anonymous> (/Users/jessie/Documents/Projects/test/node_modules/uglify-js/tools/node.js:20:1),
> ```
> 
> and here is the config
> 
> ```js
> import alias from 'rollup-plugin-alias';
> import resolve from 'rollup-plugin-node-resolve';
> import commonjs from 'rollup-plugin-commonjs';
> import babel from 'rollup-plugin-babel';
> import {uglify} from 'rollup-plugin-uglify';
> import builtins from 'rollup-plugin-node-builtins';
> import paths from './paths';
> 
> const name = 'test';
> const banner = '';
> 
> const baseConfig = {
>     input: 'src/index.js',
>     plugins: [
>         alias({
>             resolve: ['.js']
>         }),
>         resolve(),
>         babel({
>             exclude: 'node_modules/**',
>             runtimeHelpers: true
>         }),
>         commonjs(),
>         builtins(),
>         process.env.NODE_ENV === 'production' && uglify()
>     ]
> };
> export default [
>     {
>         ...baseConfig,
>         output: [
>             {
>                 name,
>                 file: `${paths.output}/${name}.js`,
>                 format: 'umd',
>                 sourcemap: true
>             },
>             // cjs and esm version
>             {
>                 file: `${paths.output}/${name}.cjs.js`,
>                 format: 'cjs',
>                 banner
>             },
>             // cjs and esm version
>             {
>                 file: `${paths.output}/${name}.esm.js`,
>                 format: 'es',
>                 banner
>             }
>         ]
>     },
>     // .min.js
>     {
>         ...baseConfig,
>         output: [
>             // umd with compress version
>             {
>                 file: `dist/${name}.min.js`,
>                 format: 'umd',
>                 name,
>                 banner
>             }
>         ]
>     }
> ];
> ```
> 
> .babelrc
> 
> ```json
> {
>     "presets": [
>         [
>             "@babel/env",
>             {
>                 "modules": false
>             }
>         ]
>     ],
>     "plugins": [
>         "@babel/proposal-object-rest-spread"
>     ]
> }
> ```
> 
> deps:
> 
> ```json
> "dependencies": {
>     "jsondiffpatch": "^0.3.11"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.2.0",
>     "@babel/plugin-external-helpers": "^7.2.0",
>     "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
>     "@babel/preset-env": "^7.2.0",
>     "babel-eslint": "^10.0.1",
>     "babel-loader": "^8.0.4",
>     "chalk": "^2.4.1",
>     "clean-webpack-plugin": "^1.0.0",
>     "cross-env": "^5.2.0",
>     "eslint": "^5.9.0",
>     "eslint-config-airbnb-base": "^13.1.0",
>     "eslint-import-resolver-webpack": "^0.10.1",
>     "eslint-plugin-import": "^2.14.0",
>     "rimraf": "^2.6.2",
>     "rollup": "^0.67.4",
>     "rollup-plugin-alias": "^1.4.0",
>     "rollup-plugin-babel": "^4.0.3",
>     "rollup-plugin-commonjs": "^9.2.0",
>     "rollup-plugin-node-builtins": "^2.1.2",
>     "rollup-plugin-node-resolve": "^3.4.0",
>     "rollup-plugin-uglify": "^6.0.0"
>   }
> ```
> 
> I can't figure out why.....Please help to check this.

I guess it's jsondiffpatch. I change the uglify to terser,then it's fixed

**Comment by lukastaegert** [comment]
Closing as I believe this is not related to rollup-plugin-json. Feel free to reopen if you disagree.
