### ISSUE TITLE
Generated quote style

### ISSUE THREAD

**Issue by TriMoon** [rollup/rollup-plugin-json#56]
Is there anyway to customize the quoting style used in the output of this plugin?
eg. make it use single quotes instead of the current double quotes?

Currently the below source:
```js
import {
	name
	,version
} from '../package.json'

const _MODULE_NAME = name.split('/')[1]
const _MODULE_VERSION = version
...
```
Produces: (using: `plugins: json({preferConst: true})` )
```js
const name = "<pkg.name>";		// content replaced for example
const version = "<pkg.version>";	// content replaced for example
...
```

While viewing the generated code in my editor (atom-beta) using eslint, i get errors from my `quotes` config.
I know there are more issues with linting generated code from rollup, but this is, together with the extra semicolons after each line that i also disallow, that bothers me at moment...

**Comment by shellscape** [comment]
The best route here with regard to eslint is to create an `.eslintrcignore` which ignores the files that are being complained about by the plugin, or to configure rules specifically for the output directory that the file lands in. At this time, we have no plans to add an option to change the quote style. We're going to be moving this plugin to a new monorepo at `rollup/plugins` soon, and a PR to add this feature would be reviewed, but likely not a high priority.
